version: '3'
services:
  db_postgres_tcc:
    build: ./db/
    ports:
      - "5433:5432"
  python_tcc:
    build: .
    links:
      - db_postgres_tcc
    volumes:
      - .:/app/
      - /etc/localtime:/etc/localtime:ro
  neo4j_tcc:
    image: neo4j
    volumes:
      - ./db/neo4j/csv:/var/lib/neo4j/import
    ports:
      - "7474:7474"
      - "7687:7687"
